# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/timing.xdc

# XDC: new/pin.xdc

# Block Designs: bd/encoder_system/encoder_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==encoder_system || ORIG_REF_NAME==encoder_system} -quiet] -quiet

# IP: bd/encoder_system/ip/encoder_system_processing_system7_0_0/encoder_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==encoder_system_processing_system7_0_0 || ORIG_REF_NAME==encoder_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/encoder_system/ip/encoder_system_axi_spi_interface_0_0/encoder_system_axi_spi_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==encoder_system_axi_spi_interface_0_0 || ORIG_REF_NAME==encoder_system_axi_spi_interface_0_0} -quiet] -quiet

# IP: bd/encoder_system/ip/encoder_system_clk_wiz_0_0/encoder_system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==encoder_system_clk_wiz_0_0 || ORIG_REF_NAME==encoder_system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/encoder_system/ip/encoder_system_ps7_0_axi_periph_0/encoder_system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==encoder_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==encoder_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/encoder_system/ip/encoder_system_rst_ps7_0_100M_0/encoder_system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==encoder_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==encoder_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/encoder_system/ip/encoder_system_auto_pc_0/encoder_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==encoder_system_auto_pc_0 || ORIG_REF_NAME==encoder_system_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_board_zedtest/encoder_board_zedtest.gen/sources_1/bd/encoder_system/ip/encoder_system_processing_system7_0_0/encoder_system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==encoder_system_processing_system7_0_0 || ORIG_REF_NAME==encoder_system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_board_zedtest/encoder_board_zedtest.gen/sources_1/bd/encoder_system/ip/encoder_system_clk_wiz_0_0/encoder_system_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==encoder_system_clk_wiz_0_0 || ORIG_REF_NAME==encoder_system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_board_zedtest/encoder_board_zedtest.gen/sources_1/bd/encoder_system/ip/encoder_system_clk_wiz_0_0/encoder_system_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==encoder_system_clk_wiz_0_0 || ORIG_REF_NAME==encoder_system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_board_zedtest/encoder_board_zedtest.gen/sources_1/bd/encoder_system/ip/encoder_system_clk_wiz_0_0/encoder_system_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_board_zedtest/encoder_board_zedtest.gen/sources_1/bd/encoder_system/ip/encoder_system_rst_ps7_0_100M_0/encoder_system_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==encoder_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==encoder_system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_board_zedtest/encoder_board_zedtest.gen/sources_1/bd/encoder_system/ip/encoder_system_rst_ps7_0_100M_0/encoder_system_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==encoder_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==encoder_system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_board_zedtest/encoder_board_zedtest.gen/sources_1/bd/encoder_system/ip/encoder_system_auto_pc_0/encoder_system_auto_pc_0_ooc.xdc

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_board_zedtest/encoder_board_zedtest.gen/sources_1/bd/encoder_system/encoder_system_ooc.xdc
