# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/timing.xdc

# XDC: imports/new/pin.xdc

# XDC: imports/new/ila.xdc

# Block Designs: bd/system_test_v3/system_test_v3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_test_v3 || ORIG_REF_NAME==system_test_v3} -quiet] -quiet

# IP: bd/system_test_v3/ip/system_test_v3_clk_wiz_1_0/system_test_v3_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_test_v3_clk_wiz_1_0 || ORIG_REF_NAME==system_test_v3_clk_wiz_1_0} -quiet] -quiet

# IP: bd/system_test_v3/ip/system_test_v3_processing_system7_0_0/system_test_v3_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_test_v3_processing_system7_0_0 || ORIG_REF_NAME==system_test_v3_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_test_v3/ip/system_test_v3_ps7_0_axi_periph_0/system_test_v3_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_test_v3_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_test_v3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system_test_v3/ip/system_test_v3_rst_ps7_0_100M_0/system_test_v3_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_test_v3_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_test_v3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system_test_v3/ip/system_test_v3_axi_spi_interface_0_0/system_test_v3_axi_spi_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_test_v3_axi_spi_interface_0_0 || ORIG_REF_NAME==system_test_v3_axi_spi_interface_0_0} -quiet] -quiet

# IP: bd/system_test_v3/ip/system_test_v3_decoder_top_v3_0_0/system_test_v3_decoder_top_v3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_test_v3_decoder_top_v3_0_0 || ORIG_REF_NAME==system_test_v3_decoder_top_v3_0_0} -quiet] -quiet

# IP: bd/system_test_v3/ip/system_test_v3_auto_pc_0/system_test_v3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_test_v3_auto_pc_0 || ORIG_REF_NAME==system_test_v3_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_clk_wiz_1_0/system_test_v3_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_test_v3_clk_wiz_1_0 || ORIG_REF_NAME==system_test_v3_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_clk_wiz_1_0/system_test_v3_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_test_v3_clk_wiz_1_0 || ORIG_REF_NAME==system_test_v3_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_clk_wiz_1_0/system_test_v3_clk_wiz_1_0_ooc.xdc

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_processing_system7_0_0/system_test_v3_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_test_v3_processing_system7_0_0 || ORIG_REF_NAME==system_test_v3_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_rst_ps7_0_100M_0/system_test_v3_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_test_v3_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_test_v3_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_rst_ps7_0_100M_0/system_test_v3_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_test_v3_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_test_v3_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_decoder_top_v3_0_0/src/timing.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_test_v3_decoder_top_v3_0_0 || ORIG_REF_NAME==system_test_v3_decoder_top_v3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_decoder_top_v3_0_0/src/timing_ooc.xdc

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_auto_pc_0/system_test_v3_auto_pc_0_ooc.xdc

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/system_test_v3_ooc.xdc
