set_property SRC_FILE_INFO {cfile:c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_clk_wiz_1_0/system_test_v3_clk_wiz_1_0.xdc rfile:../../../encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_clk_wiz_1_0/system_test_v3_clk_wiz_1_0.xdc id:1 order:EARLY scoped_inst:system_test_v3_i/clk_wiz_1/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_processing_system7_0_0/system_test_v3_processing_system7_0_0.xdc rfile:../../../encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_processing_system7_0_0/system_test_v3_processing_system7_0_0.xdc id:2 order:EARLY scoped_inst:system_test_v3_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.srcs/constrs_2_ila/imports/new/timing.xdc rfile:../../../encoder_decoder_test_v3.srcs/constrs_2_ila/imports/new/timing.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.srcs/constrs_2_ila/imports/new/pin.xdc rfile:../../../encoder_decoder_test_v3.srcs/constrs_2_ila/imports/new/pin.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.srcs/constrs_2_ila/imports/new/ila.xdc rfile:../../../encoder_decoder_test_v3.srcs/constrs_2_ila/imports/new/ila.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/encoder_decoder_test_v3/encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_decoder_top_v3_0_0/src/timing.xdc rfile:../../../encoder_decoder_test_v3.gen/sources_1/bd/system_test_v3/ip/system_test_v3_decoder_top_v3_0_0/src/timing.xdc id:6 order:LATE scoped_inst:system_test_v3_i/decoder_top_v3_0/inst} [current_design]
current_instance system_test_v3_i/clk_wiz_1/inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.080
current_instance
current_instance system_test_v3_i/processing_system7_0/inst
set_property src_info {type:SCOPED_XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C11" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C10" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B13" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B14" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D16" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B15" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F13" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E12" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C17" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D14" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C18" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A10" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A11" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F12" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A12" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D15" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A14" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E16" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C15" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C13" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C16" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D13" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A15" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F15" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:2 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A16" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B17" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F14" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A17" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D10" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:2 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B18" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:2 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A19" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C5" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E8" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:2 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D9" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:2 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C6" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:2 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E9" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:2 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:2 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D5" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:2 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D8" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:2 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A5" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:2 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A6" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:2 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B7" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:2 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D6" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B8" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E6" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H5" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:2 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G5" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:2 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M5" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:2 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P4" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:2 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N5" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:2 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B4" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:2 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W5" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R2" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G2" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C2" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W4" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T2" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F2" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B2" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E3" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:2 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E2" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:2 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E1" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:2 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C1" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:2 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D1" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:2 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D3" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:2 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A4" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V3" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:2 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V2" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:2 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A2" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W3" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:2 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y2" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:2 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y4" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:2 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W1" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:2 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y3" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:2 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V1" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:2 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U3" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:2 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U2" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:2 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U4" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:2 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T4" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:2 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B3" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R1" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:2 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R3" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:2 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P3" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:2 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P1" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:2 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J1" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:2 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H1" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:2 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H2" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:2 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J3" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:2 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H3" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:2 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G3" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:2 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C3" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y1" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T1" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F1" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A1" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N1" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:2 line:627 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N3" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:2 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L2" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:2 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M2" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:2 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P5" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:2 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J5" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R4" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:651 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L5" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J4" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:2 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K1" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:2 line:663 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K4" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:2 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L4" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:2 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L1" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:2 line:675 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M4" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:2 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K3" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:2 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M3" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:2 line:687 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K2" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F4" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:2 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D4" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:2 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E4" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:2 line:703 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G4" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:2 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F5" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:2 line:711 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N2" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:2 line:715 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:2 line:718 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:2 line:721 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E7" [get_ports "PS_CLK"]
current_instance
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name dec_spiClk_out -source [get_pins -of [get_cells -hier ODDR_inst -filter {name =~ "*decoder_top*/inst*"}] -filter {ref_pin_name == C}] -divide_by 1 [get_ports dec_spi_clk_fb]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_0]]" 20.0
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_0]]" 10.0
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_180]]" 20.0
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_180]]" 10.0
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_fb_0]]" 20.0
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_fb_0]]" 10.0
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_0]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" 20.0
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_0]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" 10.0
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_180]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" 20.0
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_180]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" 10.0
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_fb_0]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" 20.0
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_fb_0]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/s00_axi_aclk]]" 10.0
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_180]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_fb_0]]" 10.0
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_180]]" -to "[get_clocks -of_objects [get_pins system_test_v3_i/axi_spi_interface_0/inst/gen_spi_clk_fb_0]]" 0
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -of [get_cells -hier spi_clk_en_reg_reg -filter {name =~ "*axi_spi_interface*/inst*"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier ODDR_inst -filter {name =~ "*axi_spi_interface*/inst*"}] -filter {ref_pin_name == CE}] 2
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -of [get_cells -hier spi_clk_en_reg_reg -filter {name =~ "*axi_spi_interface*/inst*"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier ODDR_inst -filter {name =~ "*axi_spi_interface*/inst*"}] -filter {ref_pin_name == CE}] 0
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_ports axi_spi_miso] -to [get_pins -of [get_cells -hier in_buffer_reg_reg[0] -filter {name =~ "*axi_spi_interface*/inst*"}] -filter {ref_pin_name == D}] "3"
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_ports axi_spi_miso] -to [get_pins -of [get_cells -hier in_buffer_reg_reg[0] -filter {name =~ "*axi_spi_interface*/inst*"}] -filter {ref_pin_name == D}] "0"
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -of [get_cells -hier spi_out_oddr -filter {name =~ "*decoder_top*/inst*"}] -filter {ref_pin_name == C}] -to [get_ports dec_spi_miso] "4.5"
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -of [get_cells -hier spi_out_oddr -filter {name =~ "*decoder_top*/inst*"}] -filter {ref_pin_name == C}] -to [get_ports dec_spi_miso] "2.0"
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports dec_reset_n] -to [all_registers -clock spiClk]
set_property src_info {type:XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports dec_sys_clk]
set_property src_info {type:XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports locked]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports ARESET_N]
set_property src_info {type:XDC file:4 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports axi_spi_mosi]
set_property src_info {type:XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports axi_spi_miso]
set_property src_info {type:XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports axi_spi_cs_n]
set_property src_info {type:XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports axi_spi_clk]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports spi_slave_reset_n]
set_property src_info {type:XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports dec_spi_mosi]
set_property src_info {type:XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports dec_spi_miso]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports dec_spi_cs_n]
set_property src_info {type:XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports dec_spi_clk]
set_property src_info {type:XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports dec_reset_n]
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {errors_corrected[0]}]
set_property src_info {type:XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {errors_corrected[1]}]
set_property src_info {type:XDC file:4 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {errors_corrected[2]}]
set_property src_info {type:XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {errors_corrected[3]}]
set_property src_info {type:XDC file:5 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:5 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:5 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:5 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list system_test_v3_i/clk_wiz_1/inst/clk_out3]]
set_property src_info {type:XDC file:5 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:5 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:5 line:41 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[0]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[1]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[2]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[3]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[4]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[5]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[6]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[7]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[8]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[9]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[10]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[11]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[12]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[13]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[14]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[15]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[16]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[17]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[18]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[19]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[20]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[21]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[22]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[23]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[24]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[25]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[26]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[27]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[28]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[29]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[30]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/driver_out_data[31]}]]
set_property src_info {type:XDC file:5 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:5 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:5 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_test_v3_i/decoder_top_v3_0/inst/spi_wr_addr[0]} {system_test_v3_i/decoder_top_v3_0/inst/spi_wr_addr[1]} {system_test_v3_i/decoder_top_v3_0/inst/spi_wr_addr[2]} {system_test_v3_i/decoder_top_v3_0/inst/spi_wr_addr[3]}]]
set_property src_info {type:XDC file:5 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:5 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:5 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[0]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[1]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[2]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[3]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[4]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[5]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[6]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[7]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[8]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[9]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[10]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[11]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[12]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[13]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[14]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[15]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[16]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[17]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[18]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[19]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[20]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[21]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[22]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[23]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[24]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[25]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[26]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[27]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[28]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[29]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[30]} {system_test_v3_i/decoder_top_v3_0/inst/spi_data_out[31]}]]
set_property src_info {type:XDC file:5 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:5 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:5 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/in_shift_count_debug[0]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/in_shift_count_debug[1]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/in_shift_count_debug[2]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/in_shift_count_debug[3]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/in_shift_count_debug[4]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/in_shift_count_debug[5]}]]
set_property src_info {type:XDC file:5 line:54 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:5 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:5 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[0]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[1]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[2]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[3]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[4]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[5]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[6]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[7]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[8]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[9]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[10]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[11]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[12]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[13]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[14]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[15]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[16]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[17]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[18]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[19]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[20]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[21]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[22]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[23]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[24]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[25]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[26]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[27]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[28]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[29]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[30]} {system_test_v3_i/decoder_top_v3_0/inst/spi_interface/miso_reg[31]}]]
set_property src_info {type:XDC file:5 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:5 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:5 line:61 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list system_test_v3_i/decoder_top_v3_0/inst/spi_interface/distru_n]]
set_property src_info {type:XDC file:5 line:62 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:5 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:5 line:65 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list system_test_v3_i/decoder_top_v3_0/inst/spi_interface/distru_p]]
set_property src_info {type:XDC file:5 line:66 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:5 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:5 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list system_test_v3_i/decoder_top_v3_0/inst/spi_interface/spi_clk_iob]]
set_property src_info {type:XDC file:5 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:5 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:5 line:73 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list system_test_v3_i/decoder_top_v3_0/inst/spi_cs_n_buffered]]
set_property src_info {type:XDC file:5 line:74 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:5 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:5 line:77 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list system_test_v3_i/decoder_top_v3_0/inst/spi_interface/spi_n_data]]
set_property src_info {type:XDC file:5 line:78 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:5 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:5 line:81 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list system_test_v3_i/decoder_top_v3_0/inst/spi_interface/spi_p_data]]
set_property src_info {type:XDC file:5 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:5 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:5 line:85 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list system_test_v3_i/decoder_top_v3_0/inst/spi_read_en_stable]]
set_property src_info {type:XDC file:5 line:86 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:5 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:5 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:5 line:89 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list system_test_v3_i/decoder_top_v3_0/inst/spi_write_en_stable]]
set_property src_info {type:XDC file:5 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:5 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:5 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:5 line:93 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out3]
current_instance system_test_v3_i/decoder_top_v3_0/inst
set_property src_info {type:SCOPED_XDC file:6 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -of [get_cells -hier * -filter {name =~ "*spi_p_valid_reg"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier * -filter {name =~ "*spi_p*_valid_metaguard_reg[0]"}] -filter {ref_pin_name == D}] 3.0
set_property src_info {type:SCOPED_XDC file:6 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -of [get_cells -hier * -filter {name =~ "*spi_p_valid_reg"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier * -filter {name =~ "*spi_p*_valid_metaguard_reg[0]"}] -filter {ref_pin_name == D}] 1.5
set_property src_info {type:SCOPED_XDC file:6 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -of [get_cells -hier * -filter {name =~ "*spi_n_valid_reg"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier * -filter {name =~ "*spi_n*_valid_metaguard_reg[0]"}] -filter {ref_pin_name == D}] 3.0
set_property src_info {type:SCOPED_XDC file:6 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -of [get_cells -hier * -filter {name =~ "*spi_n_valid_reg"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier * -filter {name =~ "*spi_n*_valid_metaguard_reg[0]"}] -filter {ref_pin_name == D}] 1.5
set_property src_info {type:SCOPED_XDC file:6 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -of [get_cells -hier * -filter {name =~ "*spi_in_iddr"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier * -filter {name =~ "*spi_*_data_metaguard_reg[0]"}] -filter {ref_pin_name == D}] 3.0
set_property src_info {type:SCOPED_XDC file:6 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -of [get_cells -hier * -filter {name =~ "*spi_in_iddr"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier * -filter {name =~ "*spi_*_data_metaguard_reg[0]"}] -filter {ref_pin_name == D}] 1.5
set_property src_info {type:SCOPED_XDC file:6 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -of [get_cells -hier * -filter {name =~ "*spi_io_regs_en_reg"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier [list "spi_out_oddr" "spi_in_iddr"] -filter {name =~ "*decoder_top*/inst*"}] -filter {ref_pin_name == CE}] 3.0
set_property src_info {type:SCOPED_XDC file:6 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -of [get_cells -hier * -filter {name =~ "*spi_io_regs_en_reg"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier [list "spi_out_oddr" "spi_in_iddr"] -filter {name =~ "*decoder_top*/inst*"}] -filter {ref_pin_name == CE}] 1.5
set_property src_info {type:SCOPED_XDC file:6 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -of [get_cells -hier * -filter {name =~ "*distru_p_reg"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier "spi_out_oddr" -filter {name =~ "*decoder_top*/inst*"}] -filter {ref_pin_name == D1}] 3.0
set_property src_info {type:SCOPED_XDC file:6 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -of [get_cells -hier * -filter {name =~ "*distru_p_reg"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier "spi_out_oddr" -filter {name =~ "*decoder_top*/inst*"}] -filter {ref_pin_name == D1}] 1.5
set_property src_info {type:SCOPED_XDC file:6 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -of [get_cells -hier * -filter {name =~ "*distru_n_reg"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier "spi_out_oddr" -filter {name =~ "*decoder_top*/inst*"}] -filter {ref_pin_name == D2}] 3.0
set_property src_info {type:SCOPED_XDC file:6 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -of [get_cells -hier * -filter {name =~ "*distru_n_reg"}] -filter {ref_pin_name == C}] -to [get_pins -of [get_cells -hier "spi_out_oddr" -filter {name =~ "*decoder_top*/inst*"}] -filter {ref_pin_name == D2}] 1.5
set_property src_info {type:SCOPED_XDC file:6 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -of [get_cells -hier * -filter {name =~ "*miso_disable_reg_reg"}] -filter {ref_pin_name == C}] -to [get_ports spi_miso] 10.0
set_property src_info {type:SCOPED_XDC file:6 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_min_delay -from [get_pins -of [get_cells -hier * -filter {name =~ "*miso_disable_reg_reg"}] -filter {ref_pin_name == C}] -to [get_ports spi_miso] 1.5
