# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/timing.xdc

# XDC: new/pin.xdc

# Block Designs: bd/decoder_sys/decoder_sys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==decoder_sys || ORIG_REF_NAME==decoder_sys} -quiet] -quiet

# IP: bd/decoder_sys/ip/decoder_sys_clk_wiz_0_0/decoder_sys_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==decoder_sys_clk_wiz_0_0 || ORIG_REF_NAME==decoder_sys_clk_wiz_0_0} -quiet] -quiet

# IP: bd/decoder_sys/ip/decoder_sys_decoder_top_v3_0_0/decoder_sys_decoder_top_v3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==decoder_sys_decoder_top_v3_0_0 || ORIG_REF_NAME==decoder_sys_decoder_top_v3_0_0} -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/decoder_board/decoder_board.gen/sources_1/bd/decoder_sys/ip/decoder_sys_clk_wiz_0_0/decoder_sys_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==decoder_sys_clk_wiz_0_0 || ORIG_REF_NAME==decoder_sys_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/decoder_board/decoder_board.gen/sources_1/bd/decoder_sys/ip/decoder_sys_clk_wiz_0_0/decoder_sys_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==decoder_sys_clk_wiz_0_0 || ORIG_REF_NAME==decoder_sys_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/decoder_board/decoder_board.gen/sources_1/bd/decoder_sys/ip/decoder_sys_clk_wiz_0_0/decoder_sys_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/decoder_board/decoder_board.gen/sources_1/bd/decoder_sys/ip/decoder_sys_decoder_top_v3_0_0/src/timing.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==decoder_sys_decoder_top_v3_0_0 || ORIG_REF_NAME==decoder_sys_decoder_top_v3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/decoder_board/decoder_board.gen/sources_1/bd/decoder_sys/ip/decoder_sys_decoder_top_v3_0_0/src/timing_ooc.xdc

# XDC: c:/Users/91988/Documents/Amruth/Files/EAS/hls_accel/decoder_board/decoder_board.gen/sources_1/bd/decoder_sys/decoder_sys_ooc.xdc
